# Generated by Django 3.0.4 on 2020-05-07 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_auto_20200404_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutive', models.CharField(blank=True, max_length=10, null=True, verbose_name='Consecutivo')),
                ('time', models.CharField(blank=True, choices=[('1', 'Hora'), ('2', 'Día'), ('3', 'Mes')], default=2, max_length=20, null=True, verbose_name='Rango de tarifas')),
                ('subject', models.CharField(blank=True, max_length=300, null=True, verbose_name='Objeto')),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Porcentaje IVA')),
                ('aiu_over', models.CharField(blank=True, choices=[('1', 'Presupuesto'), ('2', 'APU')], max_length=50, null=True, verbose_name='Aplicar AIU sobre')),
                ('rev_number', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Numero de revisión')),
                ('delivery_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiempo de entrega')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('administration_percentage', models.SmallIntegerField(blank=True, null=True, verbose_name='Porcentaje de administración')),
                ('incidentals_percentaje', models.SmallIntegerField(blank=True, null=True, verbose_name='Porcentaje de imprevistos')),
                ('utility_percentage', models.SmallIntegerField(blank=True, null=True, verbose_name='Porcentaje de utilidad')),
                ('incidentals', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('administration', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('utility', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_direct_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_indirect_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('iva_option', models.CharField(blank=True, choices=[('1', 'Subtotal'), ('2', 'Utilidad')], max_length=50, null=True, verbose_name='Calcular IVA sobre')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'presupuesto',
                'verbose_name_plural': 'presupuestos',
            },
        ),
        migrations.CreateModel(
            name='BudgetSubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('amount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('rev_number', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Numero de revisión')),
                ('unit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('apu_exists', models.BooleanField(default=False)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
            ],
            options={
                'verbose_name': 'subitem de presupuesto',
                'verbose_name_plural': 'subitems de presupuesto',
            },
        ),
        migrations.CreateModel(
            name='BudgetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'tipo de presupuesto',
                'verbose_name_plural': 'tipos de presupuesto',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(default='Colombia', max_length=50)),
                ('state', models.CharField(default='Bolívar', max_length=50)),
                ('city', models.CharField(default='Cartagena', max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daily_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'equipo/herramienta',
                'verbose_name_plural': 'equipos/herramientas',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daily_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiales',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('value', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'tipo de riesgo',
                'verbose_name_plural': 'tipos de riesgo',
            },
        ),
        migrations.CreateModel(
            name='Secure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daily_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'seguro/otro',
                'verbose_name_plural': 'seguros/otros',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('budget_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.BudgetType')),
            ],
            options={
                'verbose_name': 'tipo de servicio',
                'verbose_name_plural': 'tipos de servicio',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daily_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'transporte',
                'verbose_name_plural': 'transportes',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'unidad',
                'verbose_name_plural': 'unidades',
            },
        ),
        migrations.CreateModel(
            name='Workforce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('experience_time', models.CharField(blank=True, choices=[(None, 'Años de experiencia'), ('0-3', '0-3 años'), ('3', '3 años'), ('+3', '+3 años'), ('3-5', '3-5 años'), ('5', '5 años'), ('+5', '+5 años'), ('5-10', '5-10 años'), ('10', '10 años'), ('+10', '+10 años')], max_length=20, null=True, verbose_name='Años de experiencia')),
                ('daily_salary', models.DecimalField(decimal_places=2, help_text='ATENCIÓN: Esta cifra siempre debe terminar con dos decimales y no se colocan punto de mil o millón.', max_digits=15, verbose_name='Salario por día')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Service')),
            ],
            options={
                'verbose_name': 'mano de obra',
                'verbose_name_plural': 'manos de obra',
            },
        ),
        migrations.CreateModel(
            name='WorkforceAPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('performance', models.DecimalField(decimal_places=2, max_digits=3)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.BudgetSubItem')),
                ('workforce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Workforce')),
            ],
            options={
                'verbose_name': 'APU Mano de obra',
            },
        ),
        migrations.CreateModel(
            name='TransportAPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('performance', models.DecimalField(decimal_places=2, max_digits=3)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.BudgetSubItem')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Transport')),
            ],
            options={
                'verbose_name': 'APU Transporte',
            },
        ),
        migrations.CreateModel(
            name='SubtotalAPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workforce', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('material', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('equipment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('transport', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('secure', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
                ('subitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.BudgetSubItem')),
            ],
            options={
                'verbose_name': 'General APU data',
            },
        ),
        migrations.CreateModel(
            name='SecureAPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('performance', models.DecimalField(decimal_places=2, max_digits=3)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('secure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Secure')),
                ('subitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.BudgetSubItem')),
            ],
            options={
                'verbose_name': 'APU Seguros y otros',
            },
        ),
        migrations.CreateModel(
            name='MaterialAPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Material')),
                ('subitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.BudgetSubItem')),
            ],
            options={
                'verbose_name': 'APU Materiales',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='service',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='budget.Service'),
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Unit'),
        ),
        migrations.CreateModel(
            name='EquipmentAPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('performance', models.DecimalField(decimal_places=2, max_digits=3)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Equipment')),
                ('subitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.BudgetSubItem')),
            ],
            options={
                'verbose_name': 'APU Equipos y herramientas',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budget.Service'),
        ),
        migrations.AddField(
            model_name='budgetsubitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Unit'),
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
                ('subitems', models.ManyToManyField(to='budget.BudgetSubItem')),
            ],
            options={
                'verbose_name': 'item de presupuesto',
                'verbose_name_plural': 'items de presupuesto',
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='budget',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Profile'),
        ),
        migrations.AddField(
            model_name='budget',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Risk', verbose_name='Riesgo de la empresa'),
        ),
        migrations.AddField(
            model_name='budget',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Service', verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='budget',
            name='typeOf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.BudgetType'),
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('service', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='budget.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('unit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='budget.ActivityCategory')),
                ('service', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='budget.Service')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Unit')),
            ],
        ),
    ]
