# Generated by Django 3.0.4 on 2020-03-30 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(default='Colombia', max_length=50)),
                ('state', models.CharField(default='Bolívar', max_length=50)),
                ('city', models.CharField(default='Cartagena', max_length=50)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'tipo de servicio',
                'verbose_name_plural': 'tipos de servicio',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=300, null=True)),
                ('total_direct_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('administration_percentage', models.SmallIntegerField(verbose_name='Porcentaje de administración')),
                ('administration', models.DecimalField(decimal_places=2, max_digits=15)),
                ('incidentals_percentaje', models.SmallIntegerField(verbose_name='Porcentaje de imprevistos')),
                ('incidentals', models.DecimalField(decimal_places=2, max_digits=15)),
                ('utility_percentage', models.SmallIntegerField(verbose_name='Porcentaje de utilidad')),
                ('utility', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_indirect_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('iva_option', models.CharField(choices=[(None, 'Calcular iva con respecto a'), (1, 'SUBTOTAL'), (2, 'XXXXXXXX')], max_length=50, verbose_name='Calcular IVA sobre')),
                ('iva', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Service')),
            ],
            options={
                'verbose_name': 'presupuesto',
                'verbose_name_plural': 'presupuestos',
            },
        ),
    ]
