# Generated by Django 3.0.4 on 2020-05-07 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='typeOf',
        ),
    ]
