# Generated by Django 3.0.4 on 2020-03-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20200330_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetalMechanicWorkforce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('experience_time', models.CharField(choices=[(None, 'Años de experiencia'), (1, '3'), (2, '+3'), (2, '3-5'), (3, '5'), (4, '+5'), (5, '10'), (6, '+10')], max_length=10)),
                ('daily_salary', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Salario por día')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
            ],
            options={
                'verbose_name': 'precio de mano de obra de metalmecánica',
                'verbose_name_plural': 'precios de mano de obra de metalmecánica',
            },
        ),
    ]
