# Generated by Django 3.0.4 on 2020-05-07 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_budget_typeof'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='typeOf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.BudgetType'),
        ),
    ]
