# Generated by Django 3.0.4 on 2020-03-29 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20200329_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'tipo de servicio',
                'verbose_name_plural': 'tipos de servicio',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=300, null=True)),
                ('total_direct_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('administration_percentage', models.SmallIntegerField()),
                ('administration', models.DecimalField(decimal_places=2, max_digits=15)),
                ('incidentals_percentaje', models.SmallIntegerField()),
                ('incidentals', models.DecimalField(decimal_places=2, max_digits=15)),
                ('utility_percentage', models.SmallIntegerField()),
                ('utility', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_indirect_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('iva_option', models.CharField(choices=[(1, 'SUBTOTAL'), (2, 'XXXXXXXX')], max_length=50)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Clients')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Services')),
            ],
        ),
    ]
