# Generated by Django 3.0.4 on 2020-03-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20200330_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metalmechanicworkforce',
            name='experience_time',
            field=models.CharField(choices=[(None, 'Años de experiencia'), (1, '3'), (2, '+3'), (3, '3-5'), (4, '5'), (5, '+5'), (6, '10'), (7, '+10')], max_length=30),
        ),
    ]
