# Generated by Django 3.0.4 on 2020-03-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20200329_0149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'presupuesto', 'verbose_name_plural': 'presupuestos'},
        ),
        migrations.AddField(
            model_name='budget',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
