# Generated by Django 3.0.4 on 2020-03-30 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_auto_20200330_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('value', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'tipo de riesgo',
                'verbose_name_plural': 'tipos de riesgo',
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[(None, 'Periodo de tiempo'), (1, 'Por hora'), (2, 'Por día'), (3, 'Mensual')], default=2, max_length=20),
        ),
        migrations.AlterField(
            model_name='metalmechanicworkforce',
            name='daily_salary',
            field=models.DecimalField(decimal_places=2, help_text='ATENCIÓN: Esta cifra siempre debe terminar con dos decimales y no se colocan punto de mil o millón.', max_digits=15, verbose_name='Salario por día'),
        ),
        migrations.AddField(
            model_name='budget',
            name='risk',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='budget.Risk'),
        ),
    ]
