# Generated by Django 3.0.4 on 2020-03-30 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_auto_20200330_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workforce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('experience_time', models.CharField(blank=True, choices=[(None, 'Años de experiencia'), ('0-3', '0-3 años'), ('3', '3 años'), ('+3', '+3 años'), ('3-5', '3-5 años'), ('5', '5 años'), ('+5', '+5 años'), ('5-10', '5-10 años'), ('10', '10 años'), ('+10', '+10 años')], max_length=20, null=True, verbose_name='Años de experiencia')),
                ('daily_salary', models.DecimalField(decimal_places=2, help_text='ATENCIÓN: Esta cifra siempre debe terminar con dos decimales y no se colocan punto de mil o millón.', max_digits=15, verbose_name='Salario por día')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('service', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='budget.Service')),
            ],
            options={
                'verbose_name': 'mano de obra',
                'verbose_name_plural': 'manos de obra',
            },
        ),
        migrations.DeleteModel(
            name='MetalMechanicWorkforce',
        ),
    ]
