# Generated by Django 3.0.4 on 2020-03-30 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_auto_20200330_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workforce',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Service'),
        ),
    ]
