# Generated by Django 3.0.4 on 2020-04-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_auto_20200330_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='iva_option',
            field=models.CharField(choices=[(None, 'Calcular IVA con respecto a'), (1, 'Subtotal'), (2, 'XXXXXXXX')], max_length=50, verbose_name='Calcular IVA sobre'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[(None, 'Periodo de tiempo'), ('1', 'Por hora'), ('2', 'Por día'), ('3', 'Mensual')], max_length=20),
        ),
    ]
