# Generated by Django 3.0.4 on 2020-04-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_auto_20200331_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='iva_option',
            field=models.CharField(choices=[(None, 'Calcular IVA con respecto a'), ('1', 'Subtotal'), ('2', 'XXXXXXXX')], max_length=50, verbose_name='Calcular IVA sobre'),
        ),
    ]
