# Generated by Django 3.0.4 on 2020-04-01 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_auto_20200331_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='period',
            new_name='time',
        ),
    ]
