# Generated by Django 3.0.4 on 2020-04-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0018_auto_20200331_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='total_indirect_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
