# Generated by Django 3.0.4 on 2020-04-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0020_auto_20200331_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='administration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='incidentals',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
