# Generated by Django 3.0.4 on 2020-04-01 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0022_budgetitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budget.Unit'),
        ),
    ]
