# Generated by Django 3.0.4 on 2020-04-01 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0025_auto_20200401_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Unit'),
        ),
    ]
