# Generated by Django 3.0.4 on 2020-04-01 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0026_auto_20200401_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetitem',
            options={'verbose_name': 'Item de presupuesto', 'verbose_name_plural': 'Items de presupuesto'},
        ),
    ]
