# Generated by Django 3.0.4 on 2020-04-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0028_auto_20200401_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
