# Generated by Django 3.0.4 on 2020-04-02 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0029_auto_20200402_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('slug', models.SlugField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Service')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Unit')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiales',
            },
        ),
    ]
