# Generated by Django 3.0.4 on 2020-04-02 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0030_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budget.Service'),
        ),
    ]
