# Generated by Django 3.0.4 on 2020-04-02 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0034_auto_20200402_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
