# Generated by Django 3.0.4 on 2020-04-02 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0035_auto_20200402_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daily_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budget.Service')),
            ],
            options={
                'verbose_name': 'equipo/herramienta',
                'verbose_name_plural': 'equipos/herramientas',
            },
        ),
    ]
