# Generated by Django 3.0.4 on 2020-04-02 21:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0038_secure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetitem',
            options={'verbose_name': 'BudgetItem', 'verbose_name_plural': 'BudgetItems'},
        ),
        migrations.RenameField(
            model_name='budgetitem',
            old_name='title',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='total_value',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='unit_value',
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BudgetSubItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Budget')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.BudgetItem')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Unit')),
            ],
            options={
                'verbose_name': 'Item de presupuesto',
                'verbose_name_plural': 'Items de presupuesto',
            },
        ),
    ]
