# Generated by Django 3.0.4 on 2020-04-03 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0040_auto_20200402_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetsubitem',
            options={'verbose_name': 'subitem de presupuesto', 'verbose_name_plural': 'subitems de presupuesto'},
        ),
        migrations.RenameField(
            model_name='budgetsubitem',
            old_name='title',
            new_name='description',
        ),
    ]
