# Generated by Django 3.0.4 on 2020-04-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0042_auto_20200402_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='duration',
            field=models.SmallIntegerField(default=1, verbose_name='Duración(días)'),
        ),
    ]
