# Generated by Django 3.0.4 on 2020-04-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0043_budgetitem_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='duration',
            field=models.SmallIntegerField(verbose_name='Duración(días)'),
        ),
    ]
