# Generated by Django 3.0.4 on 2020-04-10 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0044_auto_20200406_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetitem',
            options={'verbose_name': 'item de presupuesto', 'verbose_name_plural': 'items de presupuesto'},
        ),
        migrations.AlterField(
            model_name='budget',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Client'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Risk'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.Service'),
        ),
    ]
