# Generated by Django 3.0.4 on 2020-04-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0045_auto_20200409_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='administration_percentage',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Porcentaje de administración'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='incidentals_percentaje',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Porcentaje de imprevistos'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='iva_option',
            field=models.CharField(blank=True, choices=[(None, 'Calcular IVA con respecto a'), ('1', 'Subtotal'), ('2', 'Utilidad')], max_length=50, null=True, verbose_name='Calcular IVA sobre'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='time',
            field=models.CharField(blank=True, choices=[(None, 'Periodo de tiempo'), ('1', 'Por hora'), ('2', 'Por día'), ('3', 'Mensual')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='utility_percentage',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Porcentaje de utilidad'),
        ),
    ]
