# Generated by Django 3.0.4 on 2020-04-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0046_auto_20200409_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetsubitem',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='budgetsubitem',
            name='item',
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='subitems',
            field=models.ManyToManyField(to='budget.BudgetSubItem'),
        ),
    ]
