# Generated by Django 3.0.4 on 2020-04-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0047_auto_20200410_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='consecutive',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
