# Generated by Django 3.0.4 on 2020-04-13 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200404_0252'),
        ('budget', '0048_budget_consecutive'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='created_by',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='home.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='iva_option',
            field=models.CharField(blank=True, choices=[('1', 'Subtotal'), ('2', 'Utilidad')], max_length=50, null=True, verbose_name='Calcular IVA sobre'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='time',
            field=models.CharField(blank=True, choices=[('1', 'Por hora'), ('2', 'Por día'), ('3', 'Mensual')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='WorkforceAPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('daily_salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('performance', models.PositiveSmallIntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.BudgetSubItem')),
                ('workforce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Workforce')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
