# Generated by Django 3.0.4 on 2020-04-13 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0049_auto_20200412_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workforceapu',
            old_name='daily_salary',
            new_name='daily_price',
        ),
        migrations.CreateModel(
            name='TransportAPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('performance', models.PositiveSmallIntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.BudgetSubItem')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Transport')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='SecureAPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('performance', models.PositiveSmallIntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('secure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Secure')),
                ('subitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.BudgetSubItem')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='MaterialAPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('performance', models.PositiveSmallIntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Material')),
                ('subitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.BudgetSubItem')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='EquipmentAPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('performance', models.PositiveSmallIntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Equipment')),
                ('subitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.BudgetSubItem')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
