# Generated by Django 3.0.4 on 2020-04-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0051_auto_20200413_0142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentapu',
            options={'verbose_name': 'APU Equipos y herramientas'},
        ),
        migrations.AlterModelOptions(
            name='materialapu',
            options={'verbose_name': 'APU Materiales'},
        ),
        migrations.AlterModelOptions(
            name='secureapu',
            options={'verbose_name': 'APU Seguros y otros'},
        ),
        migrations.AlterModelOptions(
            name='transportapu',
            options={'verbose_name': 'APU Transporte'},
        ),
        migrations.AlterModelOptions(
            name='workforceapu',
            options={'verbose_name': 'APU Mano de obra'},
        ),
        migrations.AlterField(
            model_name='equipmentapu',
            name='performance',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='secureapu',
            name='performance',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='transportapu',
            name='performance',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='workforceapu',
            name='performance',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
