# Generated by Django 3.0.4 on 2020-04-13 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0052_auto_20200413_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetsubitem',
            name='budget',
            field=models.ForeignKey(default=68, on_delete=django.db.models.deletion.CASCADE, to='budget.Budget'),
            preserve_default=False,
        ),
    ]
