# Generated by Django 3.0.4 on 2020-04-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0055_budgetsubitem_apu_exist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetsubitem',
            old_name='apu_exist',
            new_name='apu_exists',
        ),
    ]
