# Generated by Django 3.0.4 on 2020-04-16 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0056_auto_20200413_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='duration',
        ),
    ]
