# Generated by Django 3.0.4 on 2020-04-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0057_remove_budgetitem_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetsubitem',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
