# Generated by Django 3.0.4 on 2020-04-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0059_auto_20200417_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetsubitem',
            name='rev_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Numero de revisión'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Porcentaje IVA'),
        ),
    ]
