# Generated by Django 3.0.4 on 2020-04-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0061_budgetsubitem_delivery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetsubitem',
            name='delivery_time',
        ),
        migrations.AlterField(
            model_name='budget',
            name='rev_number',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Numero de revisión'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='time',
            field=models.CharField(blank=True, choices=[('1', 'Hora'), ('2', 'Día'), ('3', 'Mes')], max_length=20, null=True, verbose_name='Rango de tarifas'),
        ),
        migrations.AlterField(
            model_name='budgetsubitem',
            name='rev_number',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Numero de revisión'),
        ),
        migrations.AlterField(
            model_name='material',
            name='service',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='budget.Service'),
        ),
    ]
