# Generated by Django 3.0.4 on 2020-05-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0062_auto_20200425_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='typeOf',
            field=models.CharField(choices=[('1', 'APU'), ('2', 'Actividades')], default=1, max_length=20, verbose_name='Tipo de presupuesto'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='time',
            field=models.CharField(blank=True, choices=[('1', 'Hora'), ('2', 'Día'), ('3', 'Mes')], default=2, max_length=20, null=True, verbose_name='Rango de tarifas'),
        ),
    ]
